// Compiles src/i18n/locales/*.json (English text -> translation) and src/i18n/packs/*.json
// (demo request parser vocabulary) into src/i18n/generated.ts, so no JSON has to ship at runtime.
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
const root = new URL('..', import.meta.url).pathname;
const read = (dir: string) => {
  const d = join(root, 'src/i18n', dir);
  const out: Record<string, unknown> = {};
  if (existsSync(d)) for (const f of readdirSync(d).filter((x) => x.endsWith('.json')).sort()) out[f.replace('.json', '')] = JSON.parse(readFileSync(join(d, f), 'utf8'));
  return out;
};
const catalogs = read('locales');
const packs = read('packs');
const body = `// GENERATED by scripts/i18n-build.ts from src/i18n/locales and src/i18n/packs. Do not edit by hand.
import type { LangPack } from './types.js';
export const CATALOGS: Record<string, Record<string, string>> = ${JSON.stringify(catalogs)};
export const PACKS: Record<string, LangPack> = ${JSON.stringify(packs)} as any;
`;
writeFileSync(join(root, 'src/i18n/generated.ts'), body);
console.log('catalogs:', Object.entries(catalogs).map(([k, v]) => `${k}=${Object.keys(v as object).length}`).join(' '), '| packs:', Object.keys(packs).join(' '));
